CREATE TABLE products (id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, name TEXT NOT NULL, quantity NUMERIC, price NUMERIC NOT NULL, description TEXT NOT NULL);

SELECT * FROM products;

ALTER TABLE products ADD photo BLOB;

CREATE TABLE users (id INTEGER PRIMARY KEY AUTO_INCREMENT, username TEXT NOT NULL, hash TEXT NOT NULL );

ALTER TABLE users ADD money NUMERIC DEFAULT 0.00;


UPDATE users SET money = 50.50 WHERE username='rox';

DELETE FROM users WHERE id=5;